CREATE DATABASE `bidding`  DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'bidding'@'localhost' IDENTIFIED BY 'mypwd';

GRANT USAGE ON *.* TO 'bidding'@'localhost' WITH MAX_QUERIES_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `bidding`.* TO 'bidding'@'localhost';

GRANT GRANT OPTION ON `bidding`.* TO 'bidding'@'localhost';

